### PR TITLE
Support for new bcs output layout 

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
This PR is addressing changes implemented in [GEOSgcm_GridComp PR#729](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/729). Changes in that PR affect boundary conditions package output layout. To be able to do restart remapping using python tools we developed we had to add support for that new bcs output structure. 

Updated 12 May 2023 by @gmao-rreichle: Applied "Contingent - DNA" label to indicate that this PR should be merged **after** PR #14.  @sdrabenh, please remove "Contingent - DNA" label when you're ready to merge this PR.

### CODE REVIEW

**Comment by biljanaorescanin** [comment]
Sure I will work on this and let you know

**Review by gmao-rreichle — APPROVED** [review]

**Comment by gmao-rreichle** [comment]
My latest commit merged branch `hotfix/mathomp4/fix-topo-link` into branch `feature/wjiang/new_bcs_structure` associated with the present PR.  I manually resolved a conflict in `pre/remap_restart/remap_upper.py`.
The reason for the commit was to avoid the merge conflict when this PR is merged into main after PR #14  has been merged.
Keeping my fingers crossed that I didn't mess things up.  If I did, it only impact the  remap_restarts python package and would not impact 0-diff testing in any way.

**Review by gmao-rreichle — DISMISSED** [review]

**Comment by biljanaorescanin** [comment]
@gmao-rreichle I've tested ten different cases, and all passed. Few to use the new BCS output layout. Few use the BCS legacy layout. Few stretched grids. Few to confirm regrid.pl and remap_restarts.py are zero diff for cases I've picked. I think this is good to go as it is. I didn't focus in this PR on testing very fine cases since those sometimes take a long time to start running with long q times when submitting to allnccs q.

**Comment by sanAkel** [comment]
> @gmao-rreichle I've tested ten different cases, and all passed. Few to use the new BCS output layout. Few use the BCS legacy layout. Few stretched grids. Few to confirm regrid.pl and remap_restarts.py are zero diff for cases I've picked. I think this is good to go as it is. I didn't focus in this PR on testing very fine cases since those sometimes take a long time to start running with long q times when submitting to allnccs q. 

Thank you all for testing.

Please confirm it includes ALL cases- including coupled, specifically MOM6.

**Comment by gmao-rreichle** [comment]
> Please confirm it includes ALL cases- including coupled, specifically MOM6.

@sanAkel:  I'm not sure where we are with coupled grids, but note that we still have the following pending:
https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/695
This probably still depends on some input from the coupled modeling team.

**Comment by biljanaorescanin** [comment]
@sanAkel New BCS output layout won't work with coupled grids until we tweak few more things, merge PR @gmao-rreichle referenced, and further cleanup of Python code to eliminate MOM5/MOM6 option separation. With that one, I was waiting on a few things, one MIT grid, so we do all of them together. Two, don't forget we also wait on @lcandre2 to provide updated river routing information that will produce the correct TRN file so new BCS outputs have accurate coupled grids without the need for manual updating. The old BCS legacy layout works with regrid.pl since we didn't change that and it also work with python. In short coupled grids are on our to-do list if we want to have them and use them in new layout. But soon we should have those as well.

**Comment by sanAkel** [comment]
> @sanAkel New BCS output layout won't work with coupled grids until 

Ok, @gmao-rreichle, @biljanaorescanin, can I still run withOUT: `New BCS output layout`?

**Comment by biljanaorescanin** [comment]
@sanAkel this PR doesn't break any capability `remap_restarts.py` already has. 
New output layout bcs option is added feature for python code. 
Since you use the python package you can test and check it yourself, the more people are testing something the more confidence we can have it works as we hope. I can't test all the cases and maybe in some case something is not right, I do my best to cover all the options but maybe I missed something. Please let me or @weiyuan-jiang if you find something is not right.

**Comment by biljanaorescanin** [comment]
Now that I've checked I indeed didn't run any coupled cases. I can try those and update once I know more.

**Comment by sanAkel** [comment]
> Now that I've checked I indeed didn't run any coupled cases. I can try those and update once I know more. 

Thank you @biljanaorescanin 

Tomorrow I'll clone this branch and test myself.

Will update when ✅.

**Comment by weiyuan-jiang** [comment]
> > Now that I've checked I indeed didn't run any coupled cases. I can try those and update once I know more.
> 
> Thank you @biljanaorescanin
> 
> Tomorrow I'll clone this branch and test myself.
> 
> Will update when ✅.

The algorithm searches the air grid and ocean grid for the BCs. But I found out there are too many subdirectories with the same agrid and ogrid.  For example here  /discover/nobackup/projects/gmao/ssd/aogcm/atmosphere_bcs/Icarus-NLv3/MOM6//   . I suggest to clean up the directories clean. i.e. , move those "bad", "save" to other location.

**Review by sdrabenh — DISMISSED** [review]

**Review by mathomp4 — APPROVED** [review]

**Pull request merged**
