### PR TITLE
Add new BCS version

### PR DESCRIPTION
**Pull request by biljanaorescanin**
New BCS version that includes bug fix over Argentina.  This set is same as v11 with bug fix. 

This PR is associated with 2 other PRs:
 https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/944 
https://github.com/GEOS-ESM/GEOSgcm_App/pull/616

### CODE REVIEW

**Comment by biljanaorescanin** [comment]
PR is trivially zero diff to what was before since we are just adding new option. 
PR was also tested for new option usage and that works. ( cases M2 to v12 and v12 to NL3) )

**Comment by biljanaorescanin** [comment]
@sdrabenh, @gmao-rreichle  here is un-draft. 
I think run fails are because run doesn't use develop but tag. We need develop for this to run.

**Review by gmao-rreichle — APPROVED** [review]
Looks good to me.

**Comment by mathomp4** [comment]
This seems to be the same CI issue as with https://github.com/GEOS-ESM/GEOSgcm_App/pull/616

I am working on a fix now.

**Review by mathomp4 — APPROVED** [review]

**Pull request merged**
